---
- name: Configure_service | Template system unit
  #become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
  notify: restart vector service