---
- name: Install Vector | DEB install
  #become: true
  ansible.builtin.apt:
    deb: https://packages.timber.io/vector/0.41.1/vector_0.41.1-1_amd64.deb
    state: present
  notify: restart vector service