---
- name: Vector | Install package
  ansible.builtin.include_tasks:
    file: install_{{ ansible_facts.pkg_mgr }}.yml
- name: Vector | Configure Vector
  ansible.builtin.include_tasks:
    file: configure_vector.yml
- name: Vector | Configure service
  ansible.builtin.include_tasks:
    file: configure_service.yml