---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
#  - name: c7
#    image: docker.io/pycontribs/centos:7
#    pre_build_image: true
  - name: ub
    image: docker.io/library/python:3.9-slim
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible